name: Data Processing and Email Workflow

on:
  schedule:
    - cron: '0 8 * * 1-5'
  workflow_dispatch:

jobs:
  process-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Debug Python Environment
      run: |
        which python
        python --version
        pip --version
        echo "Python path:"
        python -c "import sys; print(sys.path)"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip freeze
        python -c "import requests; print('requests version:', requests.__version__)"
        
    - name: Run data pull script
      run: python scripts/pull_data.py
      env:
        DATA_API_KEY: ${{ secrets.ORG_GFM_SECRET }}
        
    - name: Run Excel formatting script
      if: success()
      run: python scripts/format_excel.py
      
    - name: Send email
      if: success()
      run: python scripts/send_email.py
      env:
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_LIST: ${{ secrets.RECIPIENT_LIST }}

    - name: Handle Failure
      if: failure()
      run: |
        echo "Workflow failed. Sending error notification..."
        python scripts/send_error_notification.py
      env:
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
